// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Extend;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Student : IAuditable
{
    public int StudentId { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleName { get; set; }

    public string? LastName { get; set; }

    public string? Gender { get; set; }

    public string? Email { get; set; }

    public string? Phone { get; set; }

    public int? StandardId { get; set; }

    public string? Address { get; set; }

    public bool? IsActive { get; set; }

    public string? Profile { get; set; }

    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual Standard? Standard { get; set; }
}