// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Extend;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Subject : IAuditable
{
    public int SubjectId { get; set; }

    public string? SubjectName { get; set; }

    public int? StandardId { get; set; }

    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual Standard? Standard { get; set; }
}