// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Extend;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class UserRole : IAuditable
{
    public int UserRole1 { get; set; }

    public int? UserId { get; set; }

    public int? RoleId { get; set; }

    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual Role? Role { get; set; }

    public virtual User? User { get; set; }
}